// Generated by gencpp from file qt_gspeech_interface/QTrobotGspeechRequest.msg
// DO NOT EDIT!


#ifndef QT_GSPEECH_INTERFACE_MESSAGE_QTROBOTGSPEECHREQUEST_H
#define QT_GSPEECH_INTERFACE_MESSAGE_QTROBOTGSPEECHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_gspeech_interface
{
template <class ContainerAllocator>
struct QTrobotGspeechRequest_
{
  typedef QTrobotGspeechRequest_<ContainerAllocator> Type;

  QTrobotGspeechRequest_()
    : options()
    , timeout(0)  {
    }
  QTrobotGspeechRequest_(const ContainerAllocator& _alloc)
    : options(_alloc)
    , timeout(0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _options_type;
  _options_type options;

   typedef int64_t _timeout_type;
  _timeout_type timeout;





  typedef boost::shared_ptr< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QTrobotGspeechRequest_

typedef ::qt_gspeech_interface::QTrobotGspeechRequest_<std::allocator<void> > QTrobotGspeechRequest;

typedef boost::shared_ptr< ::qt_gspeech_interface::QTrobotGspeechRequest > QTrobotGspeechRequestPtr;
typedef boost::shared_ptr< ::qt_gspeech_interface::QTrobotGspeechRequest const> QTrobotGspeechRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qt_gspeech_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'qt_gspeech_interface': ['/home/qtrobot/catkin_ws/src/qt_gspeech_interface/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7905c636e3a74c1e2131e884321e218";
  }

  static const char* value(const ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7905c636e3a74c1ULL;
  static const uint64_t static_value2 = 0xe2131e884321e218ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_gspeech_interface/QTrobotGspeechRequest";
  }

  static const char* value(const ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] options\n\
int64 timeout\n\
";
  }

  static const char* value(const ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.options);
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QTrobotGspeechRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_gspeech_interface::QTrobotGspeechRequest_<ContainerAllocator>& v)
  {
    s << indent << "options[]" << std::endl;
    for (size_t i = 0; i < v.options.size(); ++i)
    {
      s << indent << "  options[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.options[i]);
    }
    s << indent << "timeout: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_GSPEECH_INTERFACE_MESSAGE_QTROBOTGSPEECHREQUEST_H
